### ISSUE TITLE
need more dynamically in configuration

### ISSUE THREAD

**Issue by rahmatputrawiranata** [mdobydullah/laraskrill#1]
can you make the configuration into params so we don't need to change the config/laraskrill.php and get the userdata from database .

btw nice work and love your work . thanks

**Comment by mdobydullah** [comment]
Thank you rahmatputrawiranata, for your feedback. I will do soon. :)

**Comment by mdobydullah** [comment]
Hello @rahmatputrawiranata, I've just released the dynamic configuration option and removed static config file.

Thanks again for your suggestion.
