### ISSUE TITLE
why i see this error!!

### ISSUE THREAD

**Issue by ZibaBahari** [mdobydullah/laraskrill#2]
"{"code":"BAD_REQUEST","message":"Already paid for 2813765570"}"

**Comment by mdobydullah** [comment]
Hello @ZibaBahari,

You've to pass custom transaction ID at the time of making payment. Set your custom transaction ID here:

```php
$this->skrilRequest->transaction_id = 'MNPTTX0001'; 
```

Replace **MNPTTX0001** with your own. You can generate this ID in many ways. Here's an example:

```php
$custom_transaction_id = "MyAppTID" . uniqid();
$this->skrilRequest->transaction_id = $custom_transaction_id '; 
```

Please try and let me know. Thanks.
