### ISSUE TITLE
this is the issue

### ISSUE THREAD

**Issue by wazirkhan306** [mdobydullah/laraskrill#3]
Header may not contain NUL bytes

**Comment by phpcodertop** [comment]
Hi,
I was having the same issue, I was using invalid test merchant. Here are a list from the documentation, you can use one of them.
My problem has been solved. Hope this helps you.

Skrill test merchant email: demoqco@sun-fish.com, demoqcoflexible@sun-fish.com, demoqcofixedhh@sun-fish.com
MQI/API password and secret word: mqi: skrill123, secretword: skrill
Skrill test card numbers: VISA: 4000001234567890 | MASTERCARD: 5438311234567890 | AMEX: 371234500012340
