### ISSUE TITLE
Header may not contain NUL bytes 

### ISSUE THREAD

**Issue by cse111** [mdobydullah/laraskrill#4]
I am getting this error after clicking on make-payment link.

Header may not contain NUL bytes

How to resolve this one?
I do dd($redirectUrl); and it output as:
b"https://pay.skrill.com?sid=\x1F‹\x08\x00\x00\x00\x00\x00\x00\x03«VJÎOIU²Rrrt‰\x0Fr

\fu

\x0EQÒQÊM-.NLOU²RòÌ+KÌÉLQ(H,JÌM-I-Rª\x05\x00ç\t“£4"

May be this is the issue, the redirect url contains garbage characters i think

**Comment by phpcodertop** [comment]
Hi,
I was having the same issue, I was using invalid test mechant. Here are a list from the documentation, you can use one of them.
My problem has been solved. Hope this helps you.

Skrill test merchant email: demoqco@sun-fish.com, demoqcoflexible@sun-fish.com, demoqcofixedhh@sun-fish.com
MQI/API password and secret word: mqi: skrill123, secretword: skrill
Skrill test card numbers: VISA: 4000001234567890 | MASTERCARD: 5438311234567890 | AMEX: 371234500012340
